apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: PostgreSQL
    type: postgres
    url: tafa-postgres:5432
    database: tafa_production
    user: tafa_admin
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: "disable"
      postgresVersion: 1600
      timescaledb: false

  - name: Redis
    type: redis-datasource
    url: tafa-redis:6380
    jsonData:
      client: standalone
    secureJsonData:
      password: ${REDIS_PASSWORD}
