// Automated Reordering Service
// Team 3: Tafa (Backend Developer)
// Features: All 8 automated reordering features

import { PrismaClient } from '@fiscalnext/database';
import { stockForecastService } from './stock-forecast.service';

const prisma = new PrismaClient();

export const autoReorderService = {
  // ===== AUTO PURCHASE ORDER GENERATION =====
  async generateAutoPurchaseOrder(params: {
    tenantId: string;
    productId: string;
    quantity: number;
    supplierId: string;
    triggeredBy: string;
    createdBy: string;
  }) {
    const { tenantId, productId, quantity, supplierId, triggeredBy, createdBy } = params;

    const poNumber = 'APO' + Date.now();

    const product = await prisma.product.findUnique({
      where: { id: productId },
      select: { name, costPrice, sku },
    });

    if (!product) throw new Error('Product not found');

    const unitCost = Number(product.costPrice) || 0;
    const lineTotal = unitCost * quantity;

    return await prisma.purchaseOrder.create({
      data: {
        tenantId,
        supplierId,
        poNumber,
        isAutoGenerated: true,
        triggeredBy,
        status: 'draft',
        subtotal: lineTotal,
        totalAmount: lineTotal,
        createdBy,
        items: {
          create: [
            {
              productId,
              productName: product.name,
              sku: product.sku,
              quantityOrdered: quantity,
              unitCost,
              lineTotal,
            },
          ],
        },
      },
      include: { items: true },
    });
  },

  // ===== MIN/MAX LEVELS =====
  async checkMinMaxLevels(tenantId: string) {
    const rules = await prisma.reorderRule.findMany({
      where: {
        tenantId,
        isActive: true,
        triggerType: 'min_max',
      },
    });

    const results = [];

    for (const rule of rules) {
      const stock = await prisma.stock.findFirst({
        where: {
          tenantId,
          productId: rule.productId,
        },
      });

      const currentQty = Number(stock?.quantity || 0);

      if (currentQty <= Number(rule.minLevel)) {
        results.push({
          ruleId: rule.id,
          productId: rule.productId,
          currentQty,
          minLevel: Number(rule.minLevel),
          reorderQty: Number(rule.reorderQty),
          shouldReorder: true,
        });
      }
    }

    return results;
  },

  async setMinMaxLevels(params: {
    tenantId: string;
    productId: string;
    minLevel: number;
    maxLevel: number;
    reorderQty: number;
    preferredSupplierId?: string;
  }) {
    const { tenantId, productId, minLevel, maxLevel, reorderQty, preferredSupplierId } = params;

    const existing = await prisma.reorderRule.findUnique({
      where: {
        tenantId_productId: {
          tenantId,
          productId,
        },
      },
    });

    if (existing) {
      return await prisma.reorderRule.update({
        where: { id: existing.id },
        data: {
          minLevel,
          maxLevel,
          reorderPoint: minLevel,
          reorderQty,
          preferredSupplierId,
        },
      });
    }

    return await prisma.reorderRule.create({
      data: {
        tenantId,
        productId,
        ruleName: `Auto-reorder for product ${productId}`,
        triggerType: 'min_max',
        minLevel,
        maxLevel,
        reorderPoint: minLevel,
        reorderQty,
        preferredSupplierId,
      },
    });
  },

  // ===== SUPPLIER SELECTION LOGIC =====
  async selectSupplier(params: {
    tenantId: string;
    productId: string;
    method?: string;
  }) {
    const { tenantId, productId, method = 'preferred' } = params;

    // Get reorder rule
    const rule = await prisma.reorderRule.findUnique({
      where: {
        tenantId_productId: {
          tenantId,
          productId,
        },
      },
    });

    if (rule?.preferredSupplierId && method === 'preferred') {
      return rule.preferredSupplierId;
    }

    // Get all suppliers who supply this product (simplified - would need supplier-product relation)
    // For now, return first active supplier
    const supplier = await prisma.vendor.findFirst({
      where: {
        tenantId,
        isActive: true,
      },
    });

    return supplier?.id || null;
  },

  async selectBestSupplier(params: {
    tenantId: string;
    productId: string;
  }): Promise<string | null> {
    const { tenantId } = params;

    // Get supplier performance metrics
    const performances = await prisma.supplierPerformance.findMany({
      where: { tenantId },
      orderBy: { performanceScore: 'desc' },
      take: 1,
    });

    return performances[0]?.supplierId || null;
  },

  // ===== ORDER CONSOLIDATION =====
  async consolidateOrders(tenantId: string, supplierId: string) {
    // Find all draft/pending auto-generated POs for this supplier
    const orders = await prisma.purchaseOrder.findMany({
      where: {
        tenantId,
        supplierId,
        isAutoGenerated: true,
        status: { in: ['draft', 'pending_approval'] },
      },
      include: { items: true },
    });

    if (orders.length <= 1) {
      return null; // Nothing to consolidate
    }

    // Create consolidated order
    const consolidatedPoNumber = 'CPO' + Date.now();
    
    const allItems = orders.flatMap(order => order.items);
    const totalAmount = allItems.reduce((sum, item) => sum + Number(item.lineTotal), 0);

    // Group items by product
    const consolidatedItems = new Map();
    allItems.forEach(item => {
      const existing = consolidatedItems.get(item.productId);
      if (existing) {
        existing.quantityOrdered += Number(item.quantityOrdered);
        existing.lineTotal += Number(item.lineTotal);
      } else {
        consolidatedItems.set(item.productId, {
          productId: item.productId,
          productName: item.productName,
          sku: item.sku,
          quantityOrdered: Number(item.quantityOrdered),
          unitCost: Number(item.unitCost),
          lineTotal: Number(item.lineTotal),
        });
      }
    });

    const consolidatedOrder = await prisma.purchaseOrder.create({
      data: {
        tenantId,
        supplierId,
        poNumber: consolidatedPoNumber,
        isAutoGenerated: true,
        triggeredBy: 'consolidation',
        status: 'draft',
        subtotal: totalAmount,
        totalAmount,
        createdBy: 'system',
        items: {
          create: Array.from(consolidatedItems.values()),
        },
      },
      include: { items: true },
    });

    // Cancel old orders
    await prisma.purchaseOrder.updateMany({
      where: {
        id: { in: orders.map(o => o.id) },
      },
      data: {
        status: 'cancelled',
      },
    });

    return consolidatedOrder;
  },

  // ===== APPROVAL WORKFLOWS =====
  async requestApproval(purchaseOrderId: string) {
    return await prisma.purchaseOrder.update({
      where: { id: purchaseOrderId },
      data: {
        requiresApproval: true,
        status: 'pending_approval',
      },
    });
  },

  async approvePurchaseOrder(purchaseOrderId: string, approvedBy: string) {
    return await prisma.purchaseOrder.update({
      where: { id: purchaseOrderId },
      data: {
        status: 'approved',
        approvedBy,
        approvedAt: new Date(),
      },
    });
  },

  async rejectPurchaseOrder(purchaseOrderId: string, reason: string) {
    return await prisma.purchaseOrder.update({
      where: { id: purchaseOrderId },
      data: {
        status: 'cancelled',
      },
    });
  },

  async getPendingApprovals(tenantId: string) {
    return await prisma.purchaseOrder.findMany({
      where: {
        tenantId,
        status: 'pending_approval',
      },
      include: {
        items: true,
      },
      orderBy: { createdAt: 'desc' },
    });
  },

  // ===== ORDER SCHEDULING =====
  async scheduleOrder(params: {
    tenantId: string;
    productId: string;
    frequency: string; // daily, weekly, monthly
    dayOfWeek?: number;
    dayOfMonth?: number;
    quantity: number;
    supplierId: string;
  }) {
    // This would integrate with a job scheduler
    // For now, just create the reorder rule
    return await this.setMinMaxLevels({
      tenantId: params.tenantId,
      productId: params.productId,
      minLevel: 0,
      maxLevel: params.quantity * 2,
      reorderQty: params.quantity,
      preferredSupplierId: params.supplierId,
    });
  },

  // ===== ORDER OPTIMIZATION =====
  async optimizeOrder(params: {
    tenantId: string;
    productId: string;
    currentQty: number;
  }) {
    const { tenantId, productId, currentQty } = params;

    // Get EOQ from forecast service
    const eoq = await stockForecastService.calculateEOQ({
      tenantId,
      productId,
    });

    // Get reorder point
    const rop = await stockForecastService.calculateReorderPoint({
      tenantId,
      productId,
    });

    return {
      shouldReorder: currentQty <= rop.reorderPoint,
      recommendedQuantity: eoq.economicOrderQuantity,
      reorderPoint: rop.reorderPoint,
      currentQty,
    };
  },

  // ===== SUPPLIER PERFORMANCE TRACKING =====
  async trackSupplierPerformance(params: {
    tenantId: string;
    supplierId: string;
    periodStart: Date;
    periodEnd: Date;
  }) {
    const { tenantId, supplierId, periodStart, periodEnd } = params;

    const orders = await prisma.purchaseOrder.findMany({
      where: {
        tenantId,
        supplierId,
        orderDate: { gte: periodStart, lte: periodEnd },
        status: { in: ['completed', 'receiving'] },
      },
      select: {
        orderDate: true,
        expectedDelivery: true,
        actualDelivery: true,
        totalAmount: true,
      },
    });

    const totalOrders = orders.length;
    let onTimeDeliveries = 0;
    let lateDeliveries = 0;
    const leadTimes: number[] = [];
    let totalPurchaseValue = 0;

    orders.forEach(order => {
      totalPurchaseValue += Number(order.totalAmount);

      if (order.actualDelivery) {
        const leadTime = (order.actualDelivery.getTime() - order.orderDate.getTime()) / (1000 * 60 * 60 * 24);
        leadTimes.push(leadTime);

        if (order.expectedDelivery) {
          if (order.actualDelivery <= order.expectedDelivery) {
            onTimeDeliveries++;
          } else {
            lateDeliveries++;
          }
        }
      }
    });

    const averageLeadTime = leadTimes.length > 0
      ? leadTimes.reduce((a, b) => a + b, 0) / leadTimes.length
      : 0;

    const onTimePercent = totalOrders > 0 ? (onTimeDeliveries / totalOrders) * 100 : 0;

    // Simple performance score calculation
    const performanceScore = (onTimePercent * 0.6) + (totalOrders > 0 ? 40 : 0);

    await prisma.supplierPerformance.create({
      data: {
        tenantId,
        supplierId,
        periodStart,
        periodEnd,
        totalOrders,
        onTimeDeliveries,
        lateDeliveries,
        averageLeadTime,
        onTimePercent,
        totalPurchaseValue,
        qualityScore: 85, // Would need quality data
        performanceScore,
      },
    });

    return {
      totalOrders,
      onTimeDeliveries,
      lateDeliveries,
      onTimePercent,
      averageLeadTime,
      performanceScore,
    };
  },

  async getSupplierPerformance(tenantId: string, supplierId: string) {
    return await prisma.supplierPerformance.findMany({
      where: { tenantId, supplierId },
      orderBy: { periodStart: 'desc' },
      take: 12, // Last 12 periods
    });
  },

  // ===== AUTOMATED REORDER EXECUTION =====
  async executeReorderRules(tenantId: string) {
    const checkResults = await this.checkMinMaxLevels(tenantId);
    const orders = [];

    for (const result of checkResults) {
      if (result.shouldReorder) {
        const rule = await prisma.reorderRule.findUnique({
          where: { id: result.ruleId },
        });

        if (!rule) continue;

        // Select supplier
        const supplierId = await this.selectSupplier({
          tenantId,
          productId: result.productId,
          method: rule.supplierSelectionMethod,
        });

        if (!supplierId) continue;

        try {
          const order = await this.generateAutoPurchaseOrder({
            tenantId,
            productId: result.productId,
            quantity: result.reorderQty,
            supplierId,
            triggeredBy: 'reorder_point',
            createdBy: 'system',
          });

          // Auto-approve if configured
          if (rule.autoApprove) {
            await this.approvePurchaseOrder(order.id, 'system');
          }

          // Update rule stats
          await prisma.reorderRule.update({
            where: { id: rule.id },
            data: {
              timesTriggered: { increment: 1 },
              lastTriggeredAt: new Date(),
            },
          });

          orders.push(order);
        } catch (error) {
          console.error('Failed to create auto-order:', error);
        }
      }
    }

    return {
      ordersCreated: orders.length,
      orders,
    };
  },

  // ===== REORDER RULE MANAGEMENT =====
  async createReorderRule(data: {
    tenantId: string;
    productId: string;
    ruleName: string;
    triggerType: string;
    minLevel: number;
    maxLevel: number;
    reorderPoint: number;
    reorderQty: number;
    preferredSupplierId?: string;
    supplierSelectionMethod?: string;
    autoApprove?: boolean;
    autoSend?: boolean;
  }) {
    return await prisma.reorderRule.create({ data });
  },

  async getReorderRules(tenantId: string) {
    return await prisma.reorderRule.findMany({
      where: { tenantId },
      orderBy: { createdAt: 'desc' },
    });
  },

  async updateReorderRule(ruleId: string, data: any) {
    return await prisma.reorderRule.update({
      where: { id: ruleId },
      data,
    });
  },

  async toggleReorderRule(ruleId: string, isActive: boolean) {
    return await prisma.reorderRule.update({
      where: { id: ruleId },
      data: { isActive },
    });
  },
};
